/* This file was automatically generated by genlex.sh
/* Do not edit!*/

#ifndef __SYMBOLS_H
#define __SYMBOLS_H

#define T_EOF 0
#define T_AND 1
#define T_BOOLEAN 2
#define T_CHOICE 3
#define T_CLOSE_PAREN 4
#define T_COMMENT 5
#define T_CONFIG 6
#define T_DEFAULT 7
#define T_DEF_BOOLEAN 8
#define T_DEF_TRISTATE 9
#define T_DEPENDS 10
#define T_ENDCHOICE 11
#define T_ENDIF 12
#define T_ENDMENU 13
#define T_EOL 14
#define T_EQUAL 15
#define T_HEX 16
#define T_IF 17
#define T_INT 18
#define T_MAINMENU 19
#define T_MENU 20
#define T_MENUCONFIG 21
#define T_NOT 22
#define T_OPEN_PAREN 23
#define T_OPTION 24
#define T_OPTIONAL 25
#define T_OR 26
#define T_PROMPT 27
#define T_RANGE 28
#define T_REQUIRES 29
#define T_SELECT 30
#define T_SOURCE 31
#define T_STRING 32
#define T_STRING_VAL 33
#define T_TRISTATE 34
#define T_UNEQUAL 35
#define T_VISIBLE_IF 36
#define T_ERROR 37

#endif
